version: '2'
services:
  app:
    build: .
    ports:
    - "8080:80"

  db:
    image: mysql
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    env_file: .env
   
